version: "3.8"

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"

    server:
        build:
            context: .
            dockerfile: ./submissionQueueHandler/Dockerfile
        ports:
            - "3000:3000"
        environment:
            - REDIS_URL=redis://redis:6379
        depends_on:
            - redis

    worker:
        build:
            context: .
            dockerfile: ./submissionWorker/Dockerfile
        ports:
            - "3001:3001"
        environment:
            - REDIS_URL=redis://redis:6379
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - server