version: '3.8'

services:
  worker:
    build:
      context: ./
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - code-sandbox-network
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  code-sandbox-network:
    external: true
