version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - code-sandbox-network

  server:
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - code-sandbox-network

networks:
  code-sandbox-network:
    external: true
